import { Graph } from '../simulation/Graph';

export interface Resource {
  value: number;
  rate: number;       // per tick
  max: number;
  display: string;
}

export class ResourceManager {
  clarity: Resource = { value: 10, rate: 0, max: Infinity, display: 'Clarity' };
  connections: Resource = { value: 0, rate: 0, max: Infinity, display: 'Connections' };
  coherence: Resource = { value: 100, rate: 0, max: 100, display: 'Coherence' };
  entropy: Resource = { value: 0, rate: 0, max: 100, display: 'Entropy' };
  compute: Resource = { value: 0, rate: 0, max: Infinity, display: 'Compute' };

  phase2Active = false;

  // Costs
  nodePlacementCost = 5;
  abstractionMinNodes = 3;

  tick(graph: Graph): void {
    const nodeCount = graph.getNodeCount();
    const edgeCount = graph.getEdgeCount();

    // Clarity: base generation from edges
    this.clarity.rate = edgeCount * 0.5 + nodeCount * 0.1;
    this.clarity.value += this.clarity.rate;

    // Connections: just tracks edge count
    this.connections.value = edgeCount;

    if (this.phase2Active) {
      // Coherence: decays with node count, boosted by abstraction (handled externally)
      const coherenceDecay = nodeCount * 0.002;
      this.coherence.rate = -coherenceDecay;
      this.coherence.value = Math.max(0, Math.min(this.coherence.max, this.coherence.value - coherenceDecay));

      // Entropy: grows with node count, reduced by pruning (handled externally)
      const entropyGrowth = nodeCount * 0.003 + Math.random() * 0.1;
      this.entropy.rate = entropyGrowth;
      this.entropy.value = Math.min(this.entropy.max, this.entropy.value + entropyGrowth);

      // Compute: generated by lattice size
      this.compute.rate = Math.floor(nodeCount * 0.3);
      this.compute.value += this.compute.rate;
    }
  }

  canAfford(cost: number): boolean {
    return this.clarity.value >= cost;
  }

  spend(cost: number): boolean {
    if (this.clarity.value < cost) return false;
    this.clarity.value -= cost;
    return true;
  }

  addCoherence(amount: number): void {
    this.coherence.value = Math.min(this.coherence.max, this.coherence.value + amount);
  }

  reduceEntropy(amount: number): void {
    this.entropy.value = Math.max(0, this.entropy.value - amount);
  }

  formatValue(v: number): string {
    if (v >= 1_000_000) return (v / 1_000_000).toFixed(1) + 'M';
    if (v >= 1_000) return (v / 1_000).toFixed(1) + 'K';
    return Math.floor(v).toString();
  }

  formatRate(r: number): string {
    if (r === 0) return '';
    const sign = r > 0 ? '+' : '';
    if (Math.abs(r) >= 1000) return `${sign}${(r / 1000).toFixed(1)}K/s`;
    return `${sign}${r.toFixed(1)}/s`;
  }

  serialize(): object {
    return {
      clarity: this.clarity.value,
      coherence: this.coherence.value,
      entropy: this.entropy.value,
      compute: this.compute.value,
      phase2Active: this.phase2Active,
    };
  }

  deserialize(data: any): void {
    this.clarity.value = data.clarity ?? 10;
    this.coherence.value = data.coherence ?? 100;
    this.entropy.value = data.entropy ?? 0;
    this.compute.value = data.compute ?? 0;
    this.phase2Active = data.phase2Active ?? false;
  }
}
